
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const LOGINSCREEN = 'LOGINSCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LOGIN_BY_EMAIL_SCREEN = 'LOGIN_BY_EMAIL_SCREEN';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';


