export const SET_NAME = "SET_NAME";
export const SET_ID = "SET_ID";
export const SET_FIRSNAME = "FIRSNAME";
export const LASTNAME = "LASTNAME";
export const SET_EMAIL = "SET_EMAIL";
export const SET_FIREBASEUID = "SET_FIREBASEUID";
export const SET_MESSAGETOKEN = "MESSAGETOKEN";
export const SET_BUISNESSNAME = "BUISNESSNAME";
export const SET_GSTNUMBER = "GSTNUMBER";
export const SET_OWNERCONTACTNUMBER = "OWNERCONTACTNUMBER";
export const SET_BUYERCONTACTNUMBER = "BUYERCONTACTNUMBER";
export const SET_DELIVERYCONTACTNUMBER = "DELIVERYCONTACTNUMBER";
export const SET_ACCOUNTSCONTACTNUMBER = "ACCOUNTSCONTACTNUMBER";


